name: Valyuta Bot

on:
  schedule:
    - cron: '0 4,8,15 * * *' # O'zbekiston vaqti: 09:00, 13:00, 20:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodni yuklab olish
        uses: actions/checkout@v3

      - name: Pythonni sozlash
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Chrome o'rnatish
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Kutubxonalarni o'rnatish
        run: |
          pip install selenium webdriver-manager requests

      - name: Botni ishga tushirish
        run: python main.py
